eshop/action_user/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'action_user'
urlpatterns = [
    path('',
         views.priv_list,
         name='my-actions'),
    path('create-restaurant',
         views.create_restaurant,
         name='create-restaurant'),
    path('show-all-restaurants',
         views.show_all_rest,
         name='show-all-restaurants'),
    path('edit-restaurant/<int:pk>',
         views.edit_restaurant,
         name='edit-restaurant'),

    path('show-restaurant/<int:pk>',
         views.show_restaurant,
         name='show-instance'),

    path('delete-restaurant/<int:pk>',
         views.delete_restaurant,
         name='delete'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('one.urls')),
                  path('user-action/', include('user_app.urls')),
                  path('priviligies/', include('action_user.urls', namespace='action_user')),
                  path('filters/', include('filters.urls', namespace='filters')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/filters/urls.py
from django.urls import path
from . import views


app_name = 'filters'
urlpatterns = [
    path('' , views.filters_index , name='filters_index'),
    path('show-phones' , views.show_phones , name='show-phones'),
    path('show-detail/<int:pk>' , views.show_detail , name='show-detail'),
    path('add-backet/<int:pk>' , views.add_backet , name='add-backet'),
    path('show_backet' , views.show_backet , name='show_backet'),
    path('delete_product/<int:pk>' , views.delete_product , name='delete_product'),
    path('clear-backet' , views.clear_backet , name='clear-backet'),
]

eshop/one/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('', views.index, name='post_list'),
    path('category /<slug:slug>', views.category_items, name='category'),
    path('test-form/', views.test_form),
    # re_path(r'^(?P<slug>[\w-]+)/$', views.post_detail, name="detail"),
    # path('', views.index),
    # re_path(r'^category/(?P<hierarchy>.+)/$', views.index, name='category'),
    # re_path(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
]

eshop/eshop/templates/includes/footer.html
<!--<footer>-->
   <!--<div>-->
       <!--<ul>-->
           <!--<li>Lorem ipsum.</li>-->
           <!--<li>Dolorem, facilis?</li>-->
           <!--<li>Neque, quos.</li>-->
           <!--<li>At, fugit.</li>-->
           <!--<li>Odit, repudiandae.</li>-->
       <!--</ul>-->
   <!--</div>-->
<!--</footer>-->

eshop/eshop/templates/includes/header.html
<header>


      {{ request.user }}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">На главную</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% for category in all_categories %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'category' slug=category.slug %}">
                        {{ category.title }}</a>
                </li>
                {% endfor %}
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Вход</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'action_user:my-actions' %}">Что я могу делать?</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выход ({{ request.user.username }})</a>
                </li>
                {% endif %}
            <li class="nav-item">
                <a href="{% url 'filters:filters_index' %}" class="nav-link">Примеры фильтров</a>


            </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'filters:show_backet' %}"> Ваша корзина ({{ request.session.backet.backet_list|length }})</a>
                </li>
            </ul>

        </div>

    </nav>
</header>