eshop/action_user/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'action_user'
urlpatterns = [
    path('',
         views.priv_list,
         name='my-actions'),
    path('create-restaurant',
         views.create_restaurant,
         name='create-restaurant'),
    path('show-all-restaurants',
         views.show_all_rest,
         name='show-all-restaurants'),
    path('edit-restaurant/<int:pk>',
         views.edit_restaurant,
         name='edit-restaurant'),

    path('show-restaurant/<int:pk>',
         views.show_restaurant,
         name='show-instance'),

    path('delete-restaurant/<int:pk>',
         views.delete_restaurant,
         name='delete'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('one.urls')),
                  path('user-action/', include('user_app.urls')),
                  path('priviligies/', include('action_user.urls', namespace='action_user')),
                  path('filters/', include('filters.urls', namespace='filters')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/one/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('', views.index, name='post_list'),
    path('category /<slug:slug>', views.category_items, name='category'),
    path('test-form/', views.test_form),
    # re_path(r'^(?P<slug>[\w-]+)/$', views.post_detail, name="detail"),
    # path('', views.index),
    # re_path(r'^category/(?P<hierarchy>.+)/$', views.index, name='category'),
    # re_path(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
]

eshop/action_user/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Resraurant(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, verbose_name='название')
    address = models.CharField(max_length=255, verbose_name='Адрес')
    description = models.TextField(max_length=1500, verbose_name='Описание')

    def __str__(self):
        return self.name


class Photo(models.Model):
    image = models.ImageField(upload_to='images')
    title = models.CharField(max_length=255)

eshop/action_user/forms.py
from django.forms import ModelForm
from .models import Resraurant


class ResraurantForm(ModelForm):
    class Meta:
        model = Resraurant
        # fields = ['name' , 'address']
        exclude = ['creator']


#

eshop/action_user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from one.views import global_ctx
from one.models import Restaurant
from .forms import ResraurantForm
from .models import Resraurant


# Create your views here.

def priv_list(request):
    ctx = {}
    if request.user.is_authenticated:
        ctx['len'] = len(Resraurant.objects.all())
        global_ctx.update(ctx)
        return render(request, 'action_user/priviligies.html', global_ctx)


def create_restaurant(request):
    ctx = {}
    form = ResraurantForm()
    ctx['form'] = form
    if request.method == "GET":
        global_ctx.update(ctx)
        return render(request,
                      'action_user/restaurant.html',
                      global_ctx)

    if request.method == 'POST':
        form = ResraurantForm(request.POST)
        if form.is_valid():
            # form_data = form.cleaned_data
            # creator = request.user
            # name = form_data['name']
            # address = form_data['address']
            # description = form_data['description']
            try:
                rest = form.save(commit=False)
                rest.creator = request.user
                rest.save()
                # Resraurant.objects.create(
                #     creator=creator,
                #     name=name,
                #     address=address,
                #     description=description,
                # )
                return redirect('action_user:my-actions')
            except Exception as e:
                ctx['error'] = e
                global_ctx.update(ctx)
                return render(request, 'action_user/restaurant.html', global_ctx)


def edit_restaurant(request, pk):
    ctx = {}
    restaurant_obj = Resraurant.objects.get(pk=pk)
    if request.method == 'GET':
        form = ResraurantForm(instance=restaurant_obj)
        ctx['form'] = form
        global_ctx.update(ctx)
        return render(request, 'action_user/edit_rest.html', global_ctx)
    elif request.method == 'POST':
        form = ResraurantForm(request.POST, instance=restaurant_obj)
        if form.is_valid():
            rest = form.save(commit=False)
            rest.creator = request.user
            rest.save()
            return redirect('action_user:my-actions')


def show_restaurant(request, pk):
    ctx = {}
    rest_object = Resraurant.objects.get(pk=pk)
    ctx['object_rest'] = rest_object
    global_ctx.update(ctx)
    return render(request , 'action_user/show_restaurant.html' ,global_ctx )



def delete_restaurant(request , pk):
    ctx = {}
    Resraurant.objects.get(pk=pk).delete()
    global_ctx.update(ctx)
    return redirect('action_user:show-all-restaurants')

def show_all_rest(request):
    ctx = {}
    all_rst = Resraurant.objects.all()
    ctx['all_rst'] = all_rst
    global_ctx.update(ctx)
    return render(request, 'action_user/all_rest.html', global_ctx)

eshop/eshop/templates/action_user/all_rest.html
{% extends 'index.html' %}


{% block body %}

<h2>Количеcтво ресторанов  - {{ all_rst|length  }}</h2>
<a class="btn btn-info" href="{% url 'action_user:my-actions' %}">Вернуться обратно к списку</a>
<hr>
{% for elem in all_rst %}
<div>

    <p>Название ресторана : {{ elem.name }}</p>
    <p>Адрес ресторана : {{ elem.address }}</p>
    <a href="{% url 'action_user:edit-restaurant' elem.id %}" class="btn btn-primary">Отредактировать</a>
    <a href="{% url 'action_user:show-instance' elem.id %}" class="btn btn-info">Просмотреть</a>
    <a href="{% url 'action_user:delete' elem.id %}" class="btn btn-danger">Удалить</a>
    <hr>
</div>
{% endfor %}
{% endblock %}

eshop/eshop/templates/action_user/edit_rest.html
{% extends 'index.html' %}

{% block body %}
<a class="btn btn-info" href="{% url 'action_user:my-actions' %}">Вернуться обратно к списку</a>
<hr>
<form action="{% url 'action_user:edit-restaurant' pk=form.instance.id %}" method="post">
    {% csrf_token %}
    {% for field in  form %}
    <div class="form-group">
        <label for="">{{field.label}}</label>
        {{field}}
    </div>
    {% endfor %}
    <button class="btn btn-primary">Сохранить!</button>
</form>
{% endblock %}

eshop/eshop/templates/action_user/priviligies.html
{% extends 'index.html' %}

{% block body %}
<div class="list-group">
  <a href="{% url 'action_user:create-restaurant' %}" class="list-group-item list-group-item-action">
       Добавить ресторан
  </a>
  <a href="{% url 'action_user:show-all-restaurants' %}" class="list-group-item list-group-item-action">Посмотреть все рестораны({{len}})</a>
</div>
{% endblock %}

eshop/eshop/templates/action_user/restaurant.html
{% extends 'index.html' %}

{% block body %}
<a class="btn btn-info" href="{% url 'action_user:my-actions' %}">Вернуться обратно к списку</a>
<hr>
<form action="{% url 'action_user:create-restaurant' %}" method="post">
    {% csrf_token %}
    {% for i in  form %}
    <div class="form-group">
        <label for="">{{i.label}}</label>
        {{i}}
    </div>
    {% endfor %}
    <button class="btn btn-primary">Сохранить!</button>
</form>


{% endblock %}

eshop/eshop/templates/action_user/show_restaurant.html
{% extends 'index.html' %}

{% block body %}
    <div class="rest-item">
        <p>Название  - {{ object_rest.name }}</p>
        <p>Адрес  - {{ object_rest.address }}</p>
        <p>Описание  - {{ object_rest.description }}</p>
    </div>
<hr>
<a class="btn btn-info" href="{% url 'action_user:my-actions' %}">Вернуться обратно к списку действий</a>
<a class="btn btn-success" href="{% url 'action_user:show-all-restaurants' %}">Вернуться обратно к списку ресторанов</a>
{% endblock %}oython