eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('one.urls')),
                  path('user-action/', include('user_app.urls')),
                  path('priviligies/', include('action_user.urls', namespace='action_user')),
                  path('filters/', include('filters.urls', namespace='filters')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/filters/urls.py
from django.urls import path
from . import views


app_name = 'filters'
urlpatterns = [
    path('' , views.filters_index , name='filters_index'),
    path('show-phones' , views.show_phones , name='show-phones'),
    path('show-detail/<int:pk>' , views.show_detail , name='show-detail'),
    path('add-backet/<int:pk>' , views.add_backet , name='add-backet'),
    path('show_backet' , views.show_backet , name='show_backet'),
    path('delete_product/<int:pk>' , views.delete_product , name='delete_product'),
    path('clear-backet' , views.clear_backet , name='clear-backet'),
]

eshop/one/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('', views.index, name='post_list'),
    path('category /<slug:slug>', views.category_items, name='category'),
    path('test-form/', views.test_form),
    # re_path(r'^(?P<slug>[\w-]+)/$', views.post_detail, name="detail"),
    # path('', views.index),
    # re_path(r'^category/(?P<hierarchy>.+)/$', views.index, name='category'),
    # re_path(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
]

eshop/filters/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.
class Phone(models.Model):
    BRAND_CHOICE = (
        ('apple', 'Apple'),
        ('samsung', 'Samsung'),
        ('nokia', 'Nokia'),
    )
    title = models.CharField(max_length=255, verbose_name='Название')
    brand = models.CharField(max_length=255, verbose_name='Бренд', choices=BRAND_CHOICE)
    model = models.CharField(max_length=255, verbose_name='Модель')
    content = RichTextField()
    price = models.FloatField(verbose_name='Цена')
    sale = models.BooleanField(default=False, verbose_name="Товар по акции?")
    sale_percent = models.PositiveIntegerField(verbose_name='На сколько процентов снизить цену?', blank=True, null=True)
    create_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images', verbose_name='Фото', default='', blank=True, null=True)

    def __str__(self):
        return self.title


    def to_dict(self):
        return {
            'id_': self.id,
            'title': self.title,
            'brand': self.brand,
            'price': self.price,
            'model': self.model,
            'sale': self.sale,
            'sale_percent': self.sale_percent,
        }

eshop/filters/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
import datetime
from .models import Phone


# Create your views here.


def filters_index(request):
    text = """lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab accusantium ad amet commodi corporis cumque delectus,
    dolor doloremque dolores doloribus eius eligendi enim ex id impedit in incidunt iste itaque laboriosam laudantium
    modi nam obcaecati omnis, pariatur, quae quibusdam quidem quod reprehenderit sint sit sunt tempora veritatis
    voluptate? Alias amet aut commodi consequuntur cumque cupiditate dolores ducimus, ea excepturi in ipsum itaque iusto
    laborum minus mollitia nam nihil placeat, quas quis quo quos rem repellendus sunt unde velit voluptate voluptatibus!
    Alias consequatur doloremque esse, eveniet facere illum labore quasi, quisquam ratione reprehenderit rerum soluta
    temporibus veniam? Consequuntur tempore unde voluptate."""
    ctx = {
        'desc': text,
        'date_var': datetime.datetime.now(),
        'list': [],
        'a': 0,
        'dict_data': {
            'people': {
                'name': 'test',
                'surname': 'test1',
                'age': 10,
            }
        }
    }
    return render(request, 'filters/filter_index.html', ctx)


def show_phones(request):
    ctx = {

    }
    all_phones = Phone.objects.all()
    ctx['all_phones'] = all_phones
    return render(request, 'filters/all_phones.html', ctx)


def show_detail(request, pk):
    ctx = {
        'object': Phone.objects.get(id=pk)
    }
    return render(request, 'filters/phone_object.html', ctx)


def add_backet(request, pk):
    phone = Phone.objects.get(id=pk)
    # backet = {
    #     'user_id': request.user.id if request.user.id else 'anonym',
    #     'backet_list': []
    # }
    # request.session['backet'] = backet
    # request.session['backet']['backet_list'].append(phone.to_dict())

    backet_list = request.session['backet']['backet_list']
    backet_list.append(phone.to_dict())
    request.session.modified = True
    return render(request, 'filters/all_phones.html', {
        'ok': True
    })


def show_backet(request):
    if request.session.get('backet'):
        backet_list = request.session.get('backet').get('backet_list')
        count_sum = 0
        sales_list = []
        for elem in backet_list:
            count_sum += elem['price']
            if elem['sale'] == True:
                sale = elem['price'], elem['sale_percent']
                sales_list.append(sale)
        sum_sales = count_sales(sales_list)
        print('asdasd', sum_sales)
        ctx = {
            'count_sum': count_sum,
            'sum_product_with_sales': sum_sales[0],
            'sum_sales': sum_sales[1],
        }
        return render(request, 'filters/backet.html', ctx)
    else:
        return render(request, 'filters/backet.html', {})


def count_sales(args):
    sum_product_with_sales = 0
    sum_sales = 0
    for elem in args:
        price, sale_per = elem[0], elem[1]
        sum_product_with_sales += price / 100 * (100 - sale_per)
        sum_sales += price / 100 * sale_per
    return sum_product_with_sales, sum_sales


def delete_product(request, pk):
    backet_list = request.session.get('backet').get('backet_list')
    copy_backet = backet_list.copy()
    print(copy_backet)
    for index, list_item in enumerate(copy_backet):
        try:
            if int(list_item['id_']) == int(pk):
                copy_backet.remove(list_item)
                break
        except Exception as e:
            print(e)
    request.session['backet']['backet_list'] = copy_backet
    return render(request, 'filters/backet.html', {})


def clear_backet(request):
    request.session.clear()
    if not request.session.get('backet'):
        backet = {
            'user_id': request.user.id if request.user.id else 'anonym',
            'backet_list': []
        }
        request.session['backet'] = backet
    return render(request, 'filters/backet.html', {})

eshop/eshop/templates/filters/all_phones.html
{% extends 'index.html' %}
{% load poll_extras %}
{% block body %}

<div class="phones-wrapper">
    {% for phone in all_phones %}
    <div class=" phone-item card {{ phone.sale|check_sale:'' }}">
        {% if phone.image %}
        <img class="card-img-top" src="{{ phone.image.url }}" alt="Card image cap">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ phone.title }}</h5>
            <p class="card-text">{{ phone.brand }}</p>
        </div>
        <ul class="list-group list-group-flush">
            {% if phone.sale %}
            <li class="list-group-item
                    {{ phone.sale|check_sale:'price' }}">
                Old price -
                {{ phone.price }} $
            </li>
            <li
                    class="list-group-item new-price">
                New price -{{ phone.price|new_price:phone.sale_percent }} $
            </li>
            {% else %}
            <li class="list-group-item ">price -{{ phone.price }} $</li>
            {% endif %}

        </ul>
        <div class="card-body">
            <a href="{% url 'filters:show-detail' phone.id %}" class="btn btn-primary">Просмотреть детальную
                информацию</a>
            <a href="{% url 'filters:add-backet' phone.id %}" onclick="confirm('Действительно вы хотите добавить товар в корзину?')" class="js-click btn btn-success">Добавить
                в корзину</a>
        </div>
    </div>
    {% endfor %}
</div>


{% if ok %}
<script>
    alert('Вы успешно добавили товар в корзину!');
</script>

{% endif %}

<style>

    .phones-wrapper {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-evenly;
        align-items: flex-start;
    }

    .sale-product {
        position: relative;
    }

    .phone-item {
        width: 33%;
    }

    .sale-product:after {
        position: absolute;
        content: 'Акция';
        font-size: 72px;
        color: blue;
        opacity: .2;
        width: 100%;
        height: 100%;
        top: -30%;
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 5;
    }

    .list-group-item.sale-price {
        text-decoration: line-through;
        background: red;
    }

    .new-price {
        color: #004085;
        background-color: #cce5ff;
        border-color: #b8daff;
    }
</style>

{% endblock %}

eshop/eshop/templates/filters/backet.html
{% extends 'index.html' %}
{% load poll_extras %}
{% block body %}
<h1>count_sum - {{ count_sum }} $</h1>
<h1>sum_product_with_sales - {{ sum_product_with_sales }} $</h1>
<h1>sum_sales - {{ sum_sales }} $</h1>
<a class="btn btn-primary " href="{% url 'filters:clear-backet'  %}">Очистить корзину</a>
{% for elem in request.session.backet.backet_list %}
<div>
    <p>Title - {{ elem.title }}</p>
    <p>Brand - {{ elem.brand }}</p>
    {% if elem.sale %}
    <p style="color: red;">New price -{{ elem.price|new_price:elem.sale_percent }} </p>
    {% endif %}
    <p>price - {{ elem.price }}</p>
    <p>Sale {{ elem.sale }}</p>
    <p>Sale percent {{ elem.sale_percent }} %</p>
    <a href="{% url 'filters:show-detail' elem.id_ %}">Show detail</a>
    <!--<a href="{% url 'filters:delete_product' elem.id_ %}">Delete from backet</a>-->
</div>
<hr>


{% endfor %}



{% endblock %}

eshop/eshop/templates/filters/filter_index.html
{% extends 'index.html' %}
{% load poll_extras %}
{% block body %}

    <div>

    </div>

    <a class="btn btn-primary" href="{% url 'filters:show-phones' %}">Перейти к телефонам</a>

    <ul>
        <li>Фильтр add - {{ 2|add:80 }}</li>
        <li>Фильтр lower - {{ "NAME"|lower }}</li>
        <li>Фильтр upper - {{ "name"|upper }}</li>
        <li>Фильтр first|upper - {{ "name"|first|upper }}</li>
        <li>Фильтр first|lower - {{ "name"|first|lower }}</li>
        <li title="{{ desc }}">Фильтр truncatewords - {{ desc|truncatewords:"30" }}</li>
        <p>{{ date_var }}</p>
        <li>дата - {{ date_var|date:'Y-m-d H:i' }}</li>
        <li>дата - {{ date_var|date:'Y-m-d H' }}</li>
        <li>дата - {{ date_var|date:'Y-m-d' }}</li>
        <li>дата - {{ date_var|date:'Y-m' }}</li>
        <li>дата - {{ date_var|date:'Y' }}</li>
    </ul>

    <h1>FOR</h1>
    <div class="wrapper">
        {% for elem in list %}
            <span class="item">{{ elem }}</span>
            {% empty %}
            <span>Список пустой</span>
        {% endfor %}
    </div>

    <h1>IF</h1>
    {% if list %}
        {% for elem in list %}
            <span class="item">{{ elem }}</span>
        {% endfor %}
    {% else %}
        <h2 style="color: red;">Списка нет!</h2>
    {% endif %}
    <h1>IF-ELIF-ELSE</h1>
    {% if a == 5 %}
        <h4 style="color: #40ff3a;">5</h4>
    {% elif a == 6 %}
        <h4 style="color: blue;">6</h4>
    {% else %}
        <h1>ELSSE!!!</h1>
    {% endif %}

    <h1>For in dict</h1>
{{ dict_data.keys }}
{{ dict_data.values }}
    {% for k, v in dict_data.items %}
        <h1>   {{ k }}</h1>

        {% for k1 , v1  in v.items %}
            <div>{{ k1 }} - {{ v1 }}</div>
        {% endfor %}
    {% endfor %}
    <h1>Custom Filters</h1>
    <ul>
        <li>
            {{ desc|custom_upper }}
        </li>
    </ul>



    <div class="wrap">
        {% for i in list %}
            <div class="item {{ forloop.counter0|add_class }}">
                <p>forloop.counter - {{ forloop.counter }}</p>
                <p>forloop.counter0 - {{ forloop.counter0 }}</p>
                <p>{{ i }}</p>
                <hr>
            </div>

        {% endfor %}
    </div>
    <style>

        .wrap {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

        .item {
            width: 50%;

        }

        .three {
            color: red;
            font-size: 24px;
            font-weight: bold;
        }

        .two {
            color: blue;
            font-size: 24px;
            font-weight: bold;
        }

        .one {
            color: green;
            font-size: 24px;
            font-weight: bold;
        }
    </style>
{% endblock %}

eshop/eshop/templates/filters/phone_object.html
{% extends 'index.html' %}
{% load poll_extras %}
{% block body %}
    <h1>{{ object.title }}</h1>
    <hr>
    <div>
        {% if object.image %}
            <img src="{{ object.image.url }}" style='max-width: 100%' alt="">
            <hr>
        {% endif %}
        <hr>

        <p> Brand -{{ object.brand }}</p>
        <hr>
        <p>Model - {{ object.model }}</p>
        <hr>
        {% if object.sale %}
            <p class="list-group-item {{ object.sale|check_sale:'price' }}">Old price -{{ object.price }} $
            </p>
            <p class="list-group-item new-price">New price -{{ object.price|new_price:object.sale_percent }} $</p>
        {% else %}
            <p class="list-group-item ">price -{{ object.price }} $</p>
        {% endif %}
        <div>
            <h3>Описание</h3>
            <div>{{ object.content|safe }}</div>
        </div>
    </div>




    <style>

        .phones-wrapper {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-evenly;
            align-items: flex-start;
        }

        .sale-product {
            position: relative;
        }

        .phone-item {
            width: 33%;
        }

        .sale-product:after {
            position: absolute;
            content: 'Акция';
            font-size: 72px;
            color: blue;
            opacity: .2;
            width: 100%;
            height: 100%;
            top: -30%;
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 5;
        }

        .list-group-item.sale-price {
            text-decoration: line-through;
            background: red;
        }

        .new-price {
            color: #004085;
            background-color: #cce5ff;
            border-color: #b8daff;
        }
    </style>

{% endblock %}